### ISSUE TITLE
Password Min Length needs to be checked properly

### ISSUE THREAD

**Issue by dhruvadeep** [udithdoddapaneni/YACC-Password-Generator#11]
Error: StreamlitAPIException: Slider min_value must be less than the max_value. The values were 32 and 32.
![streamlit](https://github.com/user-attachments/assets/4250f1e6-4bf8-4f5b-8f75-bbe404ad9aa5)

**Comment by dhruvadeep** [comment]
Additional Problem
When you keep your slider for max password length to 32 it produces a password of 31 characters.

**Comment by Nikhil422004** [comment]
Fixed this issue and one similar to it. Now the max length slider will not be displayed when the min length slider is maxed out. Additionally, none of the sliders will be displayed if all the parameters are maxed out.
Thanks for pointing it out.
