### ISSUE TITLE
Allowance of zero character password + decimal values

### ISSUE THREAD

**Issue by dhruvadeep** [udithdoddapaneni/YACC-Password-Generator#12]
![image](https://github.com/user-attachments/assets/f8f264b9-4a8e-4055-a1de-2f38ef379c61)

As any password suggester or generator, it should generate a password of some minimum length. Ideally 6 characters long. 

+ Allowing of decimal digits in input field doesn't help much and can be fixed by tight value checking or put input as 0.00:0f

**Comment by udithdoddapaneni** [comment]
zero characters is intentional but need to fix that decimal characters problem

**Comment by Nikhil422004** [comment]
Fixed the decimal characters issue. The zero input has been left so intentionally.
Thanks for the heads up.
